_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 128
image_size:
    value: 28
learning_rate:
    value: 0.01
n_channels:
    value: 1
n_epochs:
    value: 100
n_timesteps:
    value: 100
train_score:
    value: false
weight_decay:
    value: 0
