_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 128
device:
    value: cuda
learning_rate:
    value: 2e-05
log_every:
    value: 10
n_epochs:
    value: 10
sde_params:
    value:
        T_max: 1
        beta_max: 2
        beta_min: 0.01
train_score:
    value: false
weight_decay:
    value: 1e-05
